### ISSUE TITLE
IJ Does not recognize images as stack or 16-bit

### ISSUE THREAD

**Issue by kmader** [4Quant/COPD-staging#34]
ImageJ produces an error message about images not fitting stack or 16-bit requirements

**Comment by kmader** [comment]
Problem is due to images being imported as floating point slices instead of 16-bit stacks, problem solved with new table creation command

``` sql
CREATE TEMPORARY TABLE newPatientData
USING fourquant.riqae.ij_images
OPTIONS (path "sample_images/*.tif")
```

**Comment by drtjre** [comment]
Will try this morning.  TJ
