### ISSUE TITLE
Intro to IJ2

### ISSUE THREAD

**Issue by drtjre** [4Quant/COPD-staging#6]
Get overview of ImageJ2 vs ImageJ1 and its place in Ops and KNIME.  
Had a discussion on this with Curtis Rueden  Tue19Jan2016 - 08:45-09:20

**Comment by kmader** [comment]
You can look through this site: http://fiji.sc/ImgLib2_Examples
You can check out this project and open it in IntelliJ: https://github.com/imglib/imglib2-tutorials
